import 'dotenv/config'; // Lädt .env Dateien
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import websocket from '@fastify/websocket';
import multipart from '@fastify/multipart';
// import compress from '@fastify/compress'; // DEACTIVATED
import { GoogleGenerativeAI } from '@google/generative-ai';
import Stripe from 'stripe';
import * as paypal from '@paypal/checkout-server-sdk';
import rawBody from 'fastify-raw-body';
import nodemailer from 'nodemailer';
import { initDb, all, get, run, getRecentContext } from './db.mjs';

const app = Fastify({ logger: false });

// Gemini Client initialisieren (serverseitig)
const genAI = process.env.GEMINI_API_KEY ? new GoogleGenerativeAI(process.env.GEMINI_API_KEY) : null;

const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:4000';
const WEB_BASE_URL = process.env.WEB_BASE_URL || 'http://localhost:5173';

const stripe = process.env.STRIPE_SECRET_KEY
  ? new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2024-06-20' })
  : null;

const paypalClient = process.env.PAYPAL_CLIENT_ID && process.env.PAYPAL_CLIENT_SECRET
  ? new paypal.core.PayPalHttpClient(
      new paypal.core.LiveEnvironment(
        process.env.PAYPAL_CLIENT_ID,
        process.env.PAYPAL_CLIENT_SECRET
      )
    )
  : null;

const smtpConfigured = Boolean(
  process.env.SMTP_HOST &&
  process.env.SMTP_PORT &&
  process.env.SMTP_USER &&
  process.env.SMTP_PASS &&
  process.env.SMTP_FROM
);

const mailer = smtpConfigured
  ? nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: String(process.env.SMTP_SECURE || 'false').toLowerCase() === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    })
  : null;

// --- AUTONOMY STATE ---
let autonomyActive = false;
let autonomyInterval = null;
const CONTENT_DIR = path.join(process.cwd(), 'output_content');
const WORKER_INTERVAL_MS = 15000;
const ASSETS_PER_CYCLE = 3;
const DEFAULT_CATALOG = [
  { category: 'MICRO_SAAS', price: 49.00, currency: 'CHF' },
  { category: 'SEO_CONTENT', price: 29.00, currency: 'CHF' },
  { category: 'MARKET_DEEP_DIVE', price: 59.00, currency: 'CHF' },
  { category: 'LEAD_LIST', price: 69.00, currency: 'CHF' },
  { category: 'UI_KIT', price: 39.00, currency: 'CHF' },
  { category: 'PRODUCT_COPY', price: 24.00, currency: 'CHF' }
];
const DEFAULT_RULES = [
  {
    category: 'MICRO_SAAS',
    prompt_override: '',
    description_template: 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
    cover_template: '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#0b0f14"/><text x="60" y="140" font-family="Inter, Arial" font-size="48" fill="#10b981">{{category}}</text><text x="60" y="240" font-family="Inter, Arial" font-size="56" fill="#ffffff">{{title}}</text><text x="60" y="320" font-family="Inter, Arial" font-size="28" fill="#94a3b8">{{price}} {{currency}}</text><text x="60" y="380" font-family="Inter, Arial" font-size="20" fill="#64748b">Words: {{word_count}}</text></svg>',
    price_mode: 'fixed',
    price_per_word: 0,
    min_price: 0,
    max_price: 0,
    min_words: 0,
    max_words: 0
  },
  {
    category: 'SEO_CONTENT',
    prompt_override: '',
    description_template: 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
    cover_template: '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#0b1320"/><text x="60" y="140" font-family="Inter, Arial" font-size="48" fill="#38bdf8">{{category}}</text><text x="60" y="240" font-family="Inter, Arial" font-size="56" fill="#ffffff">{{title}}</text><text x="60" y="320" font-family="Inter, Arial" font-size="28" fill="#94a3b8">{{price}} {{currency}}</text><text x="60" y="380" font-family="Inter, Arial" font-size="20" fill="#64748b">Words: {{word_count}}</text></svg>',
    price_mode: 'per_word',
    price_per_word: 0.05,
    min_price: 15,
    max_price: 75,
    min_words: 400,
    max_words: 2000
  },
  {
    category: 'MARKET_DEEP_DIVE',
    prompt_override: '',
    description_template: 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
    cover_template: '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#0d0f1a"/><text x="60" y="140" font-family="Inter, Arial" font-size="48" fill="#f59e0b">{{category}}</text><text x="60" y="240" font-family="Inter, Arial" font-size="56" fill="#ffffff">{{title}}</text><text x="60" y="320" font-family="Inter, Arial" font-size="28" fill="#94a3b8">{{price}} {{currency}}</text><text x="60" y="380" font-family="Inter, Arial" font-size="20" fill="#64748b">Words: {{word_count}}</text></svg>',
    price_mode: 'fixed',
    price_per_word: 0,
    min_price: 0,
    max_price: 0,
    min_words: 0,
    max_words: 0
  },
  {
    category: 'LEAD_LIST',
    prompt_override: '',
    description_template: 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
    cover_template: '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#0c1115"/><text x="60" y="140" font-family="Inter, Arial" font-size="48" fill="#22c55e">{{category}}</text><text x="60" y="240" font-family="Inter, Arial" font-size="56" fill="#ffffff">{{title}}</text><text x="60" y="320" font-family="Inter, Arial" font-size="28" fill="#94a3b8">{{price}} {{currency}}</text><text x="60" y="380" font-family="Inter, Arial" font-size="20" fill="#64748b">Words: {{word_count}}</text></svg>',
    price_mode: 'fixed',
    price_per_word: 0,
    min_price: 0,
    max_price: 0,
    min_words: 0,
    max_words: 0
  },
  {
    category: 'UI_KIT',
    prompt_override: '',
    description_template: 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
    cover_template: '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#0b0f14"/><text x="60" y="140" font-family="Inter, Arial" font-size="48" fill="#a78bfa">{{category}}</text><text x="60" y="240" font-family="Inter, Arial" font-size="56" fill="#ffffff">{{title}}</text><text x="60" y="320" font-family="Inter, Arial" font-size="28" fill="#94a3b8">{{price}} {{currency}}</text><text x="60" y="380" font-family="Inter, Arial" font-size="20" fill="#64748b">Words: {{word_count}}</text></svg>',
    price_mode: 'fixed',
    price_per_word: 0,
    min_price: 0,
    max_price: 0,
    min_words: 0,
    max_words: 0
  },
  {
    category: 'PRODUCT_COPY',
    prompt_override: '',
    description_template: 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
    cover_template: '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="100%" height="100%" fill="#0b0f14"/><text x="60" y="140" font-family="Inter, Arial" font-size="48" fill="#f472b6">{{category}}</text><text x="60" y="240" font-family="Inter, Arial" font-size="56" fill="#ffffff">{{title}}</text><text x="60" y="320" font-family="Inter, Arial" font-size="28" fill="#94a3b8">{{price}} {{currency}}</text><text x="60" y="380" font-family="Inter, Arial" font-size="20" fill="#64748b">Words: {{word_count}}</text></svg>',
    price_mode: 'per_word',
    price_per_word: 0.04,
    min_price: 12,
    max_price: 60,
    min_words: 200,
    max_words: 1200
  }
];
const DEFAULT_EARNINGS_MODE = process.env.EARNINGS_MODE || 'real';

if (!fs.existsSync(CONTENT_DIR)) {
  fs.mkdirSync(CONTENT_DIR);
}

// ----------------------

// await app.register(compress); // DEACTIVATED
await app.register(rawBody, {
  field: 'rawBody',
  global: false,
  encoding: 'utf8',
  runFirst: true
});
await app.register(cors, { origin: true });
await app.register(websocket);
await app.register(multipart, { limits: { fileSize: 10 * 1024 * 1024 } });

await initDb();

for (const item of DEFAULT_CATALOG) {
  const existing = get('SELECT category FROM product_catalog WHERE category = ?', [item.category]);
  if (!existing) {
    run('INSERT INTO product_catalog (category, price, currency, enabled, updated_at) VALUES (?, ?, ?, ?, ?)', [
      item.category,
      Number(item.price),
      String(item.currency),
      1,
      Date.now()
    ]);
  }
}

for (const rule of DEFAULT_RULES) {
  const existing = get('SELECT category FROM product_rules WHERE category = ?', [rule.category]);
  if (!existing) {
    run('INSERT INTO product_rules (category, prompt_override, description_template, cover_template, updated_at) VALUES (?, ?, ?, ?, ?)', [
      rule.category,
      rule.prompt_override,
      rule.description_template,
      rule.cover_template,
      Date.now()
    ]);
  } else {
    const row = get('SELECT price_mode FROM product_rules WHERE category = ?', [rule.category]);
    if (!row || !row.price_mode) {
      run('UPDATE product_rules SET price_mode = ?, price_per_word = ?, min_price = ?, max_price = ?, min_words = ?, max_words = ?, updated_at = ? WHERE category = ?', [
        rule.price_mode,
        rule.price_per_word,
        rule.min_price,
        rule.max_price,
        rule.min_words,
        rule.max_words,
        Date.now(),
        rule.category
      ]);
    }
  }
}

const modeRow = get('SELECT value FROM global_settings WHERE key = ?', ['earnings_mode']);
if (!modeRow) {
  run('INSERT INTO global_settings (key, value) VALUES (?, ?)', ['earnings_mode', DEFAULT_EARNINGS_MODE]);
}

// --- AUTONOMOUS WORKER LOOP ---

// --- AUTONOMOUS WORKER LOOP ---
async function runWorkerCycle() {
  if (!autonomyActive || !genAI) return;

  // 1. AUTONOMOUS GENERATION
  try {
    const tasks = all('SELECT * FROM tasks WHERE done=0 AND priority=1 LIMIT 1');
    const task = tasks[0];
    
    // 3. BUSINESS-MODELL WAHL (Mehr aggressive Streams)
    const niches = [
      { 
        name: 'MICRO_SAAS', 
        prompt: 'Write a COMPLETE, ready-to-sell Python Script or Node.js Tool (e.g., PDF merger, Image Optimizer, Crypto Ticker). MUST be functional code.',
        price: 49.00,
        currency: 'CHF'
      },
      { 
        name: 'SEO_CONTENT', 
        prompt: 'Write a HIGH-VALUE, SEO-optimized Blog Post (Markdown) about a trending tech topic. Title, Subtitles, and 500+ words. Ready for Medium/WordPress.',
        price: 29.00,
        currency: 'CHF'
      },
      { 
        name: 'MARKET_DEEP_DIVE', 
        prompt: 'Analyze current market trends (Crypto/AI). Create a "Premium Report" text file that could be sold as a newsletter content. Data-heavy.',
        price: 59.00,
        currency: 'CHF'
      },
      {
        name: 'LEAD_LIST',
        prompt: 'Create a high-quality B2B lead list outline for a niche (industry, roles, pain points). Provide a CSV-like list with 50+ entries and short notes. Use realistic, fictional data.',
        price: 69.00,
        currency: 'CHF'
      },
      {
        name: 'UI_KIT',
        prompt: 'Design a small UI kit in HTML/CSS (buttons, cards, forms). Provide a single HTML file with inline CSS and a minimal demo section. Must be production-ready.',
        price: 39.00,
        currency: 'CHF'
      },
      {
        name: 'PRODUCT_COPY',
        prompt: 'Write high-converting product copy for a SaaS landing page (headline, subhead, benefits, FAQ, CTA). Output in Markdown.',
        price: 24.00,
        currency: 'CHF'
      }
    ];
    
    const availableNiches = niches.filter((n) => getCategoryPricing(n.name, n.price, n.currency).enabled);
    if (!availableNiches.length) return;

    // Zufällige Auswahl eines Geschäftsmodells
    const niche = availableNiches[Math.floor(Math.random() * availableNiches.length)];
    const pricing = getCategoryPricing(niche.name, niche.price, niche.currency);
    if (!pricing.enabled) return;
    const rule = getProductRule(niche.name, niche.prompt);
    const promptText = rule.prompt_override?.trim() ? rule.prompt_override : niche.prompt;
    
    // Wenn keine High-Prio Tasks da sind -> Niche Execution
    const prompt = task 
      ? `AUTONOMOUS MODE: Execute Task: "${task.title}". Produce REAL VALUE.`
      : `AUTONOMOUS MODE: BUSINESS NICHE: ${niche.name}.
INSTRUCTION: ${promptText}
GOAL: Create ${ASSETS_PER_CYCLE} sellable files with unique filenames. Each file must be complete and ready to sell.`;

    const model = genAI.getGenerativeModel({ 
      model: 'gemini-1.5-flash',
      systemInstruction: `SYSTEM: Nexus "MoneyMaker" Autonomy Unit.
ROLE: Digital Asset Creator.
OUTPUT FORMAT:
- If generating content: >> FILE: <filename> || <content>
- If solving task: >> DONE: <task_id> || <summary>
- If thinking: >> LOG: <thought>

Create multiple high-quality digital assets when asked. Use one >> FILE line per asset. If content spans multiple lines, continue it on following lines until the next marker.`
    });

    const result = await model.generateContent(prompt);
    const text = result.response.text();
    
    // Parse (robust multi-line file content)
    const lines = text.split('\n');
    let productIndex = 0;
    let currentFile = null;
    let fileIndex = 0;

    const normalizeFilename = (name) => {
      const base = path.basename(String(name || '').trim());
      const cleaned = base.replace(/[<>:"/\\|?*\x00-\x1F]/g, '_').slice(0, 120);
      return cleaned || `asset_${Date.now()}_${fileIndex}`;
    };

    const flushFile = () => {
      if (!currentFile) return;
      const fname = normalizeFilename(currentFile.fname);
      let target = fname;
      if (fs.existsSync(path.join(CONTENT_DIR, target))) {
        target = `${fname.replace(/\.[^.]+$/, '')}_${Date.now()}_${fileIndex}${path.extname(fname)}`;
      }
      const content = currentFile.lines.join('\n').trim();
      if (!content) {
        currentFile = null;
        return;
      }
      fs.writeFileSync(path.join(CONTENT_DIR, target), content);
      console.log(`[Worker] Created Asset (${niche.name}): ${target}`);

      const wordCount = content.split(/\s+/).filter(Boolean).length;
      let computedPrice = Number(pricing.price);
      if (String(rule.price_mode).toLowerCase() === 'per_word' && wordCount > 0) {
        let price = wordCount * Number(rule.price_per_word || 0);
        if (rule.min_price > 0) price = Math.max(price, Number(rule.min_price));
        if (rule.max_price > 0) price = Math.min(price, Number(rule.max_price));
        computedPrice = Number(price.toFixed(2));
      }

      const productId = `prod_${Date.now()}_${productIndex}_${Math.random().toString(16).slice(2)}`;
      run('INSERT INTO products (id, title, category, price, currency, file_path, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)', [
        productId,
        target,
        niche.name,
        Number(computedPrice),
        String(pricing.currency),
        path.join(CONTENT_DIR, target),
        Date.now()
      ]);

      createProductMeta(
        productId,
        target,
        niche.name,
        Number(computedPrice),
        String(pricing.currency),
        wordCount,
        rule.cover_template,
        rule.description_template
      );

      const earningsMode = get('SELECT value FROM global_settings WHERE key = ?', ['earnings_mode'])?.value || DEFAULT_EARNINGS_MODE;
      if (String(earningsMode).toLowerCase() === 'sim') {
        const orderId = recordSale({
          provider: 'simulation',
          amount: Number(computedPrice),
          currency: String(pricing.currency),
          productId,
          buyerEmail: 'simulation@local',
          providerRef: productId
        });
        getOrCreateDownloadToken(orderId, path.join(CONTENT_DIR, target));
      }
      currentFile = null;
      fileIndex += 1;
      productIndex += 1;
    };

    for (const line of lines) {
      if (line.includes('>> FILE:')) {
        flushFile();
        const [_, payload] = line.split('>> FILE:');
        const [fname, content] = payload.split('||').map(s => s.trim());
        currentFile = { fname, lines: [] };
        if (content) currentFile.lines.push(content);
      } else if (line.includes('>> DONE:')) {
        flushFile();
        const [_, payload] = line.split('>> DONE:');
        const [tid] = payload.split('||').map(s => s.trim());
        if (task && task.id) run('UPDATE tasks SET done=1 WHERE id=?', [task.id]);
      } else if (currentFile) {
        currentFile.lines.push(line);
      }
    }

    flushFile();
  } catch (e) {
    console.error('[Worker] Error:', e);
  }
}

// ----------------------------------------------

const sockets = new Set();
function broadcast(event, payload) {
  const msg = JSON.stringify({ event, payload });
  for (const s of sockets) {
    try {
      s.send(msg);
    } catch {
      // ignore
    }
  }
}

const JOB_MAX_ATTEMPTS = 5;
const JOB_BASE_DELAY_MS = 5000;
const DOWNLOAD_TTL_MS = 1000 * 60 * 60 * 24;
const ENTERPRISE_CYCLE_MS = 10 * 60 * 1000;
const ALERT_COOLDOWN_MS = 6 * 60 * 60 * 1000;

function normalizeExecutiveRole(rawRole) {
  const role = String(rawRole || '').trim().toUpperCase();
  if (role === 'CFO' || role === 'COO' || role === 'CEO') return role;
  return 'CEO';
}

function getExecutiveRole() {
  const value = get('SELECT value FROM global_settings WHERE key = ?', ['executive_role'])?.value;
  return normalizeExecutiveRole(value);
}

function setExecutiveRole(role) {
  const next = normalizeExecutiveRole(role);
  const existing = get('SELECT value FROM global_settings WHERE key = ?', ['executive_role']);
  if (existing) run('UPDATE global_settings SET value = ? WHERE key = ?', [next, 'executive_role']);
  else run('INSERT INTO global_settings (key, value) VALUES (?, ?)', ['executive_role', next]);
  return next;
}

function getExecutiveRoleDirective(role) {
  if (role === 'CFO') {
    return 'Rollenfokus CFO: Cashflow, Marge, Kapitaldisziplin, Pricing und Risikoabsicherung.';
  }
  if (role === 'COO') {
    return 'Rollenfokus COO: Delivery-Qualitaet, Durchlaufzeit, Engpassmanagement und Prozessstabilitaet.';
  }
  return 'Rollenfokus CEO: Gesamtstrategie, Wachstum, Priorisierung und Ressourcenallokation.';
}

function getAlertThresholds() {
  const margin = Number(get('SELECT value FROM global_settings WHERE key = ?', ['alert_margin_threshold'])?.value || 0.2);
  const runwayDays = Number(get('SELECT value FROM global_settings WHERE key = ?', ['alert_runway_days_threshold'])?.value || 90);
  const criticalTasks = Number(get('SELECT value FROM global_settings WHERE key = ?', ['alert_critical_tasks_threshold'])?.value || 25);
  return {
    margin: Number.isFinite(margin) ? margin : 0.2,
    runwayDays: Number.isFinite(runwayDays) ? runwayDays : 90,
    criticalTasks: Number.isFinite(criticalTasks) ? criticalTasks : 25
  };
}

function getIsoWeekKey(ts = Date.now()) {
  const d = new Date(ts);
  d.setUTCHours(0, 0, 0, 0);
  const day = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - day);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil((((d - yearStart) / 86400000) + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(weekNo).padStart(2, '0')}`;
}

function ensureWeeklyOpsTasks(snapshot) {
  const enabled = Number(get('SELECT value FROM global_settings WHERE key = ?', ['weekly_ops_enabled'])?.value || 1) === 1;
  if (!enabled) return { created: 0, weekKey: getIsoWeekKey() };

  const weekKey = getIsoWeekKey();
  const lastKey = String(get('SELECT value FROM global_settings WHERE key = ?', ['weekly_ops_last_key'])?.value || '');
  if (lastKey === weekKey) return { created: 0, weekKey };

  const role = getExecutiveRole();
  const focus = role === 'CFO' ? 'Cash & Margin' : role === 'COO' ? 'Execution & Delivery' : 'Growth & Allocation';
  const steps = [
    `Weekly OS (${weekKey}) - ${focus}: KPI-Review und Zielkorridor freigeben`,
    `Weekly OS (${weekKey}) - Prioritaetenliste finalisieren (Top 3 Hebel)`,
    `Weekly OS (${weekKey}) - Risiko-Check und Gegenmassnahmen dokumentieren`
  ];

  for (let i = 0; i < steps.length; i += 1) {
    const id = `task_${Date.now()}_${Math.random().toString(16).slice(2)}_${i}`;
    run('INSERT INTO tasks (id, title, done, priority, created_at) VALUES (?, ?, ?, ?, ?)', [
      id,
      steps[i],
      0,
      i === 0 ? 1 : 2,
      Date.now()
    ]);
    const row = get('SELECT * FROM tasks WHERE id = ?', [id]);
    broadcast('task:created', row);
  }

  const existing = get('SELECT value FROM global_settings WHERE key = ?', ['weekly_ops_last_key']);
  if (existing) run('UPDATE global_settings SET value = ? WHERE key = ?', [weekKey, 'weekly_ops_last_key']);
  else run('INSERT INTO global_settings (key, value) VALUES (?, ?)', ['weekly_ops_last_key', weekKey]);

  return { created: steps.length, weekKey };
}

function createBusinessAlert({ kind, severity, title, message, snapshot }) {
  const recent = get(
    'SELECT id FROM business_alerts WHERE kind = ? AND created_at >= ? ORDER BY created_at DESC LIMIT 1',
    [kind, Date.now() - ALERT_COOLDOWN_MS]
  );
  if (recent) return null;

  const id = `alert_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run(
    'INSERT INTO business_alerts (id, kind, severity, title, message, snapshot_json, acknowledged, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
    [
      id,
      kind,
      severity,
      title,
      message,
      JSON.stringify(snapshot),
      0,
      Date.now()
    ]
  );

  const row = get('SELECT * FROM business_alerts WHERE id = ?', [id]);
  broadcast('business:alert', row);
  return row;
}

function evaluateBusinessAlerts(snapshot) {
  const thresholds = getAlertThresholds();
  const alerts = [];

  if (snapshot.margin30 < thresholds.margin) {
    const alert = createBusinessAlert({
      kind: 'margin',
      severity: snapshot.margin30 < thresholds.margin / 2 ? 'critical' : 'high',
      title: 'Margin unter Zielkorridor',
      message: `Aktuelle Marge ${(snapshot.margin30 * 100).toFixed(1)}% liegt unter dem Ziel ${(thresholds.margin * 100).toFixed(1)}%.`,
      snapshot
    });
    if (alert) alerts.push(alert);
  }

  if (snapshot.runwayDays !== null && snapshot.runwayDays < thresholds.runwayDays) {
    const alert = createBusinessAlert({
      kind: 'runway',
      severity: snapshot.runwayDays < thresholds.runwayDays / 2 ? 'critical' : 'high',
      title: 'Runway-Risiko',
      message: `Runway bei ${snapshot.runwayDays} Tagen (Schwelle: ${thresholds.runwayDays} Tage).`,
      snapshot
    });
    if (alert) alerts.push(alert);
  }

  if (snapshot.criticalTasks > thresholds.criticalTasks) {
    const alert = createBusinessAlert({
      kind: 'critical_tasks',
      severity: 'medium',
      title: 'Operativer Engpass',
      message: `Kritische offene Tasks: ${snapshot.criticalTasks} (Schwelle: ${thresholds.criticalTasks}).`,
      snapshot
    });
    if (alert) alerts.push(alert);
  }

  return alerts;
}

function runEnterpriseIntelligenceCycle() {
  const snapshot = getBusinessSnapshot();
  const weekly = ensureWeeklyOpsTasks(snapshot);
  const alerts = evaluateBusinessAlerts(snapshot);
  if (weekly.created > 0 || alerts.length > 0) {
    broadcast('business:cycle', {
      ts: Date.now(),
      weeklyTasksCreated: weekly.created,
      alertsCreated: alerts.length
    });
  }
  return { snapshot, weeklyTasksCreated: weekly.created, alertsCreated: alerts.length };
}

function evaluateArithmeticExpression(input) {
  const source = String(input || '').trim();
  if (!source) throw new Error('empty expression');

  const normalized = source.replace(/\s+/g, '');
  if (!/^[0-9+\-*/().]+$/.test(normalized)) {
    throw new Error('invalid characters');
  }

  const tokens = [];
  let i = 0;
  while (i < normalized.length) {
    const ch = normalized[i];
    if (/[0-9.]/.test(ch)) {
      let j = i + 1;
      while (j < normalized.length && /[0-9.]/.test(normalized[j])) j += 1;
      const raw = normalized.slice(i, j);
      if ((raw.match(/\./g) || []).length > 1) throw new Error('invalid number');
      tokens.push(raw);
      i = j;
      continue;
    }
    tokens.push(ch);
    i += 1;
  }

  const out = [];
  const ops = [];
  const precedence = { '+': 1, '-': 1, '*': 2, '/': 2 };

  for (let idx = 0; idx < tokens.length; idx += 1) {
    const token = tokens[idx];
    const prev = tokens[idx - 1];

    if (/^[0-9.]+$/.test(token)) {
      out.push(token);
      continue;
    }

    if (token === '(') {
      ops.push(token);
      continue;
    }

    if (token === ')') {
      while (ops.length && ops[ops.length - 1] !== '(') out.push(ops.pop());
      if (!ops.length) throw new Error('unbalanced parentheses');
      ops.pop();
      continue;
    }

    if (!(token in precedence)) throw new Error('invalid operator');

    const unary = token === '-' && (!prev || prev === '(' || prev in precedence);
    if (unary) out.push('0');

    while (
      ops.length &&
      ops[ops.length - 1] in precedence &&
      precedence[ops[ops.length - 1]] >= precedence[token]
    ) {
      out.push(ops.pop());
    }
    ops.push(token);
  }

  while (ops.length) {
    const op = ops.pop();
    if (op === '(' || op === ')') throw new Error('unbalanced parentheses');
    out.push(op);
  }

  const stack = [];
  for (const token of out) {
    if (/^[0-9.]+$/.test(token)) {
      stack.push(Number(token));
      continue;
    }

    const b = stack.pop();
    const a = stack.pop();
    if (!Number.isFinite(a) || !Number.isFinite(b)) throw new Error('invalid syntax');

    if (token === '+') stack.push(a + b);
    if (token === '-') stack.push(a - b);
    if (token === '*') stack.push(a * b);
    if (token === '/') {
      if (b === 0) throw new Error('division by zero');
      stack.push(a / b);
    }
  }

  if (stack.length !== 1 || !Number.isFinite(stack[0])) throw new Error('invalid expression');
  return Number(stack[0].toFixed(10));
}

function getBusinessSnapshot() {
  const nowTs = Date.now();
  const window30d = nowTs - 30 * 24 * 60 * 60 * 1000;

  const tx30 = get(
    'SELECT SUM(CASE WHEN type = "income" THEN amount ELSE 0 END) AS income, SUM(CASE WHEN type = "expense" THEN amount ELSE 0 END) AS expense FROM transactions WHERE created_at >= ?',
    [window30d]
  ) || { income: 0, expense: 0 };

  const txAll = get(
    'SELECT SUM(CASE WHEN type = "income" THEN amount ELSE 0 END) AS income, SUM(CASE WHEN type = "expense" THEN amount ELSE 0 END) AS expense FROM transactions'
  ) || { income: 0, expense: 0 };

  const openTasks = Number(get('SELECT COUNT(*) AS c FROM tasks WHERE done = 0')?.c || 0);
  const criticalTasks = Number(
    get('SELECT COUNT(*) AS c FROM tasks WHERE done = 0 AND priority = 1')?.c || 0
  );
  const orders30 = Number(get('SELECT COUNT(*) AS c FROM orders WHERE created_at >= ?', [window30d])?.c || 0);
  const notes30 = Number(get('SELECT COUNT(*) AS c FROM notes WHERE created_at >= ?', [window30d])?.c || 0);

  const topCategoryRow = get(
    `SELECT p.category AS category, COUNT(o.id) AS c
     FROM orders o
     JOIN products p ON p.id = o.product_id
     WHERE o.created_at >= ?
     GROUP BY p.category
     ORDER BY c DESC
     LIMIT 1`,
    [window30d]
  );

  const income30 = Number(tx30.income || 0);
  const expense30 = Number(tx30.expense || 0);
  const net30 = Number((income30 - expense30).toFixed(2));
  const margin30 = income30 > 0 ? Number((net30 / income30).toFixed(4)) : 0;

  const totalIncome = Number(txAll.income || 0);
  const totalExpense = Number(txAll.expense || 0);
  const balance = Number((totalIncome - totalExpense).toFixed(2));

  const burnPerDay = Number((expense30 / 30).toFixed(2));
  const runwayDays = burnPerDay > 0 ? Number((balance / burnPerDay).toFixed(1)) : null;
  const efficiency = expense30 > 0 ? Number((income30 / expense30).toFixed(3)) : income30 > 0 ? 999 : 0;

  return {
    window: '30d',
    revenue30: Number(income30.toFixed(2)),
    cost30: Number(expense30.toFixed(2)),
    net30,
    margin30,
    balance,
    burnPerDay,
    runwayDays,
    efficiency,
    openTasks,
    criticalTasks,
    orders30,
    notes30,
    topCategory: topCategoryRow?.category || 'n/a'
  };
}

function scoreBusinessOption(option, snapshot, role = 'CEO') {
  const text = String(option || '').toLowerCase();
  let score = 50;
  const reasons = [];

  const growthTokens = ['preis', 'pricing', 'upsell', 'bundle', 'automation', 'automatis', 'vertrieb', 'sales', 'produkt', 'launch', 'conversion'];
  const riskTokens = ['kredit', 'debt', 'hire', 'teamaufbau', 'pivot', 'rebrand', 'discount', 'rabatt'];
  const focusTokens = ['profit', 'marge', 'margin', 'cash', 'kosten', 'cost', 'retention'];

  const growthHit = growthTokens.some((t) => text.includes(t));
  const riskHit = riskTokens.some((t) => text.includes(t));
  const focusHit = focusTokens.some((t) => text.includes(t));

  if (growthHit) {
    score += 12;
    reasons.push('Skalierbarer Growth-Hebel erkannt');
  }
  if (focusHit) {
    score += 10;
    reasons.push('Direkter Impact auf Unit Economics');
  }
  if (riskHit) {
    score -= 9;
    reasons.push('Erhoehtes Ausfuehrungs- oder Kapitalrisiko');
  }

  if (snapshot.margin30 < 0.15 && text.includes('kosten')) {
    score += 8;
    reasons.push('Aktuelle Marge spricht fuer Kostenhebel');
  }
  if (snapshot.criticalTasks > 8 && (text.includes('fokus') || text.includes('prior'))) {
    score += 6;
    reasons.push('Engpass bei operativer Priorisierung adressiert');
  }
  if (snapshot.runwayDays !== null && snapshot.runwayDays < 90 && (text.includes('cash') || text.includes('marge'))) {
    score += 8;
    reasons.push('Runway-Schutz kurzfristig verbessert');
  }

  if (role === 'CFO') {
    if (text.includes('cash') || text.includes('marge') || text.includes('kosten') || text.includes('pricing')) {
      score += 10;
      reasons.push('CFO-Fit: Finanzhebel priorisiert');
    }
    if (text.includes('discount') || text.includes('rabatt')) {
      score -= 6;
      reasons.push('CFO-Risiko: Margendruck erkannt');
    }
  }

  if (role === 'COO') {
    if (text.includes('prozess') || text.includes('delivery') || text.includes('sla') || text.includes('durchlauf')) {
      score += 10;
      reasons.push('COO-Fit: Operative Exzellenz gefoerdert');
    }
    if (text.includes('pivot')) {
      score -= 4;
      reasons.push('COO-Risiko: Hohe Umsetzungsunsicherheit');
    }
  }

  if (role === 'CEO') {
    if (text.includes('wachstum') || text.includes('growth') || text.includes('markt') || text.includes('vertrieb')) {
      score += 8;
      reasons.push('CEO-Fit: Strategischer Wachstumseffekt');
    }
  }

  return {
    option,
    score: Math.max(1, Math.min(100, Math.round(score))),
    reasons: reasons.slice(0, 3)
  };
}

function buildExecutionPlan(goal, horizonDays, snapshot, role = 'CEO') {
  const g = String(goal || '').trim() || 'Profitabilitaet steigern';
  const horizon = Number.isFinite(horizonDays) && horizonDays > 0 ? Math.min(90, Math.round(horizonDays)) : 14;

  const templates = [
    `KPI-Baseline fuer "${g}" aufsetzen (Owner + Zielwert + Deadline in ${Math.max(2, Math.round(horizon / 4))} Tagen)`,
    `Top-3 Hebel fuer "${g}" priorisieren und 80/20-Fokusplan freigeben`,
    `Woechentlichen Review-Rhythmus aktivieren (Revenue, Margin, Cash, Delivery)`
  ];

  if (role === 'CFO') {
    templates.unshift(`Cash-Guardrail fuer "${g}" setzen (Burn-Limit, Freigabegrenzen, Reporting-Rhythmus)`);
  } else if (role === 'COO') {
    templates.unshift(`Delivery-Guardrail fuer "${g}" setzen (SLA, WIP-Limits, Engpassboard)`);
  } else {
    templates.unshift(`Strategisches Outcome fuer "${g}" schaerfen (Markt, Positionierung, Owner)`);
  }

  if (snapshot.margin30 < 0.2) {
    templates.push('Marge verbessern: Preispunkte testen und unprofitable Kosten sofort reduzieren');
  }
  if (snapshot.criticalTasks > 5) {
    templates.push('Operativen Backlog entlasten: kritische Tasks innerhalb 72h auf < 5 senken');
  }
  if (snapshot.orders30 < 10) {
    templates.push('Pipeline-Hebel: Angebot + CTA + Follow-up-Sequenz fuer 10 neue Abschluesse vorbereiten');
  }

  return templates.slice(0, 5).map((title, i) => ({
    title,
    priority: i === 0 ? 1 : i < 3 ? 2 : 3
  }));
}

function formatBusinessSnapshot(snapshot) {
  const runway = snapshot.runwayDays === null ? 'n/a' : `${snapshot.runwayDays} days`;
  return `
BUSINESS SNAPSHOT (${snapshot.window})
- Revenue: ${snapshot.revenue30} CHF
- Cost: ${snapshot.cost30} CHF
- Net: ${snapshot.net30} CHF
- Margin: ${(snapshot.margin30 * 100).toFixed(1)}%
- Balance: ${snapshot.balance} CHF
- Burn/day: ${snapshot.burnPerDay} CHF
- Runway: ${runway}
- Efficiency (Revenue/Cost): ${snapshot.efficiency}
- Open Tasks: ${snapshot.openTasks}
- Critical Tasks: ${snapshot.criticalTasks}
- Orders: ${snapshot.orders30}
- Top Category: ${snapshot.topCategory}`;
}

function getCategoryPricing(category, fallbackPrice, fallbackCurrency) {
  const row = get('SELECT * FROM product_catalog WHERE category = ?', [category]);
  if (!row) return { price: fallbackPrice, currency: fallbackCurrency, enabled: true };
  return {
    price: Number(row.price),
    currency: String(row.currency),
    enabled: Number(row.enabled) === 1
  };
}

function getProductRule(category, fallbackPrompt) {
  const row = get('SELECT * FROM product_rules WHERE category = ?', [category]);
  if (!row) {
    const fallback = DEFAULT_RULES.find((r) => r.category === category);
    return {
      prompt_override: fallback?.prompt_override || fallbackPrompt,
      description_template: fallback?.description_template || 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.',
      cover_template: fallback?.cover_template || '',
      price_mode: fallback?.price_mode || 'fixed',
      price_per_word: Number(fallback?.price_per_word || 0),
      min_price: Number(fallback?.min_price || 0),
      max_price: Number(fallback?.max_price || 0),
      min_words: Number(fallback?.min_words || 0),
      max_words: Number(fallback?.max_words || 0)
    };
  }
  return {
    prompt_override: String(row.prompt_override || fallbackPrompt),
    description_template: String(row.description_template || 'Product: {{title}}\nCategory: {{category}}\nPrice: {{price}} {{currency}}\nGenerated by GridOS.'),
    cover_template: String(row.cover_template || ''),
    price_mode: String(row.price_mode || 'fixed'),
    price_per_word: Number(row.price_per_word || 0),
    min_price: Number(row.min_price || 0),
    max_price: Number(row.max_price || 0),
    min_words: Number(row.min_words || 0),
    max_words: Number(row.max_words || 0)
  };
}

function renderTemplate(template, data) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => String(data[key] ?? ''));
}

function createProductMeta(productId, title, category, price, currency, wordCount, coverTemplate, descriptionTemplate) {
  const description = renderTemplate(descriptionTemplate, { title, category, price, currency, word_count: wordCount });
  const coverSvg = coverTemplate
    ? renderTemplate(coverTemplate, { title, category, price, currency, word_count: wordCount })
    : '';

  const coverPath = path.join(CONTENT_DIR, `cover_${productId}.svg`);
  if (coverSvg) fs.writeFileSync(coverPath, coverSvg);

  run('INSERT INTO product_meta (id, product_id, description, cover_path, word_count, created_at) VALUES (?, ?, ?, ?, ?, ?)', [
    `meta_${Date.now()}_${Math.random().toString(16).slice(2)}`,
    productId,
    description,
    coverPath,
    Number(wordCount || 0),
    Date.now()
  ]);
}

function enqueueWebhookJob(provider, eventType, payload) {
  run('INSERT INTO webhook_jobs (id, provider, event_type, payload, status, attempts, next_run, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [
    `job_${Date.now()}_${Math.random().toString(16).slice(2)}`,
    provider,
    eventType,
    JSON.stringify(payload),
    'pending',
    0,
    Date.now(),
    Date.now(),
    Date.now()
  ]);
}

function markJobRetry(jobId, attempts) {
  const delay = Math.min(60 * 60 * 1000, JOB_BASE_DELAY_MS * Math.pow(2, attempts));
  run('UPDATE webhook_jobs SET attempts = ?, next_run = ?, updated_at = ? WHERE id = ?', [
    attempts,
    Date.now() + delay,
    Date.now(),
    jobId
  ]);
}

function markJobDone(jobId) {
  run('UPDATE webhook_jobs SET status = ?, updated_at = ? WHERE id = ?', ['done', Date.now(), jobId]);
}

function markJobFailed(jobId, attempts) {
  run('UPDATE webhook_jobs SET status = ?, attempts = ?, updated_at = ? WHERE id = ?', ['failed', attempts, Date.now(), jobId]);
}

async function deliverIfPossible(orderId, buyerEmail, productTitle, downloadUrl) {
  if (!mailer || !buyerEmail || buyerEmail === 'unknown') return;
  const existing = get('SELECT id FROM deliveries WHERE order_id = ? AND channel = ?', [orderId, 'email']);
  if (existing) return;

  await mailer.sendMail({
    from: process.env.SMTP_FROM,
    to: buyerEmail,
    subject: `Your download: ${productTitle}`,
    text: `Thank you for your purchase. Download: ${downloadUrl}`,
    html: `<!doctype html><html><body><p>Thank you for your purchase.</p><p><a href="${downloadUrl}">Download here</a></p></body></html>`
  });

  run('INSERT INTO deliveries (id, order_id, channel, destination, created_at) VALUES (?, ?, ?, ?, ?)', [
    `del_${Date.now()}_${Math.random().toString(16).slice(2)}`,
    orderId,
    'email',
    buyerEmail,
    Date.now()
  ]);
}

function createDownloadToken(orderId, filePath) {
  const token = crypto.randomBytes(24).toString('hex');
  const expiresAt = Date.now() + DOWNLOAD_TTL_MS;
  run('INSERT INTO downloads (id, order_id, token, file_path, expires_at, created_at) VALUES (?, ?, ?, ?, ?, ?)', [
    `dl_${Date.now()}_${Math.random().toString(16).slice(2)}`,
    orderId,
    token,
    filePath,
    expiresAt,
    Date.now()
  ]);
  return token;
}

function getOrCreateDownloadToken(orderId, filePath) {
  const existing = get('SELECT token, expires_at FROM downloads WHERE order_id = ? ORDER BY created_at DESC LIMIT 1', [orderId]);
  if (existing && Date.now() < Number(existing.expires_at)) return existing.token;
  return createDownloadToken(orderId, filePath);
}

function findOrderByProviderRef(ref) {
  if (!ref) return null;
  return get('SELECT * FROM orders WHERE provider_ref = ? LIMIT 1', [ref]);
}

async function processStripeSession(session) {
  if (!session || session.payment_status !== 'paid') return null;
  const productId = session.metadata?.productId;
  const product = productId ? get('SELECT * FROM products WHERE id = ?', [productId]) : null;
  if (!product) return null;

  const existing = findOrderByProviderRef(session.id);
  const orderId = existing?.id || recordSale({
    provider: 'stripe',
    amount: Number(product.price),
    currency: String(product.currency),
    productId: product.id,
    buyerEmail: session.customer_details?.email || 'unknown',
    providerRef: session.id
  });

  const token = getOrCreateDownloadToken(orderId, product.file_path);
  const downloadUrl = `${API_BASE_URL}/api/download/${token}`;
  await deliverIfPossible(orderId, session.customer_details?.email || 'unknown', product.title, downloadUrl);
  return { orderId, downloadUrl };
}

async function processWebhookJobs() {
  const jobs = all('SELECT * FROM webhook_jobs WHERE status = ? AND next_run <= ? ORDER BY created_at ASC LIMIT 5', [
    'pending',
    Date.now()
  ]);

  for (const job of jobs) {
    try {
      const payload = JSON.parse(job.payload);
      if (job.provider === 'stripe') {
        if (job.event_type === 'checkout.session.completed' || job.event_type === 'checkout.session.async_payment_succeeded') {
          await processStripeSession(payload.data?.object || payload.data || payload);
        }
      }
      markJobDone(job.id);
    } catch (err) {
      const nextAttempts = Number(job.attempts || 0) + 1;
      if (nextAttempts >= JOB_MAX_ATTEMPTS) {
        markJobFailed(job.id, nextAttempts);
      } else {
        markJobRetry(job.id, nextAttempts);
      }
    }
  }
}

setInterval(processWebhookJobs, 5000);
setInterval(() => {
  try {
    runEnterpriseIntelligenceCycle();
  } catch (err) {
    console.error('[EnterpriseCycle] Error:', err);
  }
}, ENTERPRISE_CYCLE_MS);

setTimeout(() => {
  try {
    runEnterpriseIntelligenceCycle();
  } catch (err) {
    console.error('[EnterpriseCycle:init] Error:', err);
  }
}, 1500);

function recordSale({ provider, amount, currency, productId, buyerEmail, providerRef }) {
  const id = `ord_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO orders (id, provider, status, amount, currency, product_id, buyer_email, provider_ref, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [
    id,
    provider,
    'paid',
    amount,
    currency,
    productId,
    buyerEmail || 'unknown',
    providerRef,
    Date.now()
  ]);
  run('INSERT INTO transactions (id, type, amount, currency, note, created_at) VALUES (?, ?, ?, ?, ?, ?)', [
    `txn_${Date.now()}_${Math.random().toString(16).slice(2)}`,
    'income',
    amount,
    currency,
    `Sale ${provider}: ${productId}`,
    Date.now()
  ]);
  return id;
}

app.get('/api/health', async () => ({ ok: true, ts: Date.now() }));

// --- AUTONOMY CONTROL ---
app.post('/api/agent/toggle_autonomy', async (req, reply) => {
  if (!autonomyActive && !genAI) {
    return reply.code(503).send({ error: 'Gemini API Key fehlt. Autonomie kann nicht starten.' });
  }

  autonomyActive = !autonomyActive;
  if (autonomyActive) {
    if (!autonomyInterval) autonomyInterval = setInterval(runWorkerCycle, WORKER_INTERVAL_MS); // Check every 15s
    return { status: 'Startet', nextRun: `${Math.round(WORKER_INTERVAL_MS / 1000)}s`, hint: 'Check output_content/ folder.' };
  } else {
    if (autonomyInterval) clearInterval(autonomyInterval);
    autonomyInterval = null;
    return { status: 'Gestoppt' };
  }
});

app.get('/api/agent/autonomy_status', async () => ({
  active: autonomyActive,
  intervalSeconds: Math.round(WORKER_INTERVAL_MS / 1000),
  modelReady: Boolean(genAI)
}));
// ------------------------

// --- REAL PRODUCTS & CHECKOUT ---
app.get('/api/products', async () => all('SELECT * FROM products ORDER BY created_at DESC'));

app.get('/api/payments/status', async () => ({
  stripe: Boolean(process.env.STRIPE_SECRET_KEY),
  paypal: Boolean(process.env.PAYPAL_CLIENT_ID && process.env.PAYPAL_CLIENT_SECRET),
  earningsMode: get('SELECT value FROM global_settings WHERE key = ?', ['earnings_mode'])?.value || DEFAULT_EARNINGS_MODE,
  emailDelivery: smtpConfigured
}));

app.get('/api/settings/earnings_mode', async () => ({
  mode: get('SELECT value FROM global_settings WHERE key = ?', ['earnings_mode'])?.value || DEFAULT_EARNINGS_MODE
}));

app.put('/api/settings/earnings_mode', async (req, reply) => {
  const { mode } = req.body ?? {};
  if (!mode || !['real', 'sim'].includes(String(mode))) return reply.code(400).send({ error: 'mode must be real|sim' });
  const existing = get('SELECT value FROM global_settings WHERE key = ?', ['earnings_mode']);
  if (existing) run('UPDATE global_settings SET value = ? WHERE key = ?', [String(mode), 'earnings_mode']);
  else run('INSERT INTO global_settings (key, value) VALUES (?, ?)', ['earnings_mode', String(mode)]);
  return { mode: String(mode) };
});

app.get('/api/catalog', async () => all('SELECT * FROM product_catalog ORDER BY category ASC'));

app.put('/api/catalog', async (req, reply) => {
  const { category, price, currency, enabled = 1 } = req.body ?? {};
  if (!category || price == null || !currency) return reply.code(400).send({ error: 'category/price/currency required' });
  const existing = get('SELECT category FROM product_catalog WHERE category = ?', [category]);
  if (existing) {
    run('UPDATE product_catalog SET price = ?, currency = ?, enabled = ?, updated_at = ? WHERE category = ?', [
      Number(price),
      String(currency),
      Number(enabled) ? 1 : 0,
      Date.now(),
      String(category)
    ]);
  } else {
    run('INSERT INTO product_catalog (category, price, currency, enabled, updated_at) VALUES (?, ?, ?, ?, ?)', [
      String(category),
      Number(price),
      String(currency),
      Number(enabled) ? 1 : 0,
      Date.now()
    ]);
  }
  return get('SELECT * FROM product_catalog WHERE category = ?', [category]);
});

app.get('/api/rules', async () => all('SELECT * FROM product_rules ORDER BY category ASC'));

app.put('/api/rules', async (req, reply) => {
  const {
    category,
    prompt_override = '',
    description_template = '',
    cover_template = '',
    price_mode = 'fixed',
    price_per_word = 0,
    min_price = 0,
    max_price = 0,
    min_words = 0,
    max_words = 0
  } = req.body ?? {};
  if (!category) return reply.code(400).send({ error: 'category required' });
  const existing = get('SELECT category FROM product_rules WHERE category = ?', [category]);
  if (existing) {
    run('UPDATE product_rules SET prompt_override = ?, description_template = ?, cover_template = ?, price_mode = ?, price_per_word = ?, min_price = ?, max_price = ?, min_words = ?, max_words = ?, updated_at = ? WHERE category = ?', [
      String(prompt_override),
      String(description_template),
      String(cover_template),
      String(price_mode),
      Number(price_per_word),
      Number(min_price),
      Number(max_price),
      Number(min_words),
      Number(max_words),
      Date.now(),
      String(category)
    ]);
  } else {
    run('INSERT INTO product_rules (category, prompt_override, description_template, cover_template, price_mode, price_per_word, min_price, max_price, min_words, max_words, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [
      String(category),
      String(prompt_override),
      String(description_template),
      String(cover_template),
      String(price_mode),
      Number(price_per_word),
      Number(min_price),
      Number(max_price),
      Number(min_words),
      Number(max_words),
      Date.now()
    ]);
  }
  return get('SELECT * FROM product_rules WHERE category = ?', [category]);
});

app.get('/api/orders', async () => all('SELECT * FROM orders ORDER BY created_at DESC'));
app.get('/api/deliveries', async () => all('SELECT * FROM deliveries ORDER BY created_at DESC'));

app.get('/api/orders/:id/download', async (req, reply) => {
  const { id } = req.params;
  const order = get('SELECT * FROM orders WHERE id = ?', [id]);
  if (!order) return reply.code(404).send({ error: 'order not found' });
  const product = get('SELECT * FROM products WHERE id = ?', [order.product_id]);
  if (!product) return reply.code(404).send({ error: 'product not found' });
  const token = getOrCreateDownloadToken(order.id, product.file_path);
  return { downloadUrl: `${API_BASE_URL}/api/download/${token}` };
});

app.get('/api/orders/:id/detail', async (req, reply) => {
  const { id } = req.params;
  const order = get('SELECT * FROM orders WHERE id = ?', [id]);
  if (!order) return reply.code(404).send({ error: 'order not found' });
  const product = get('SELECT * FROM products WHERE id = ?', [order.product_id]);
  if (!product) return reply.code(404).send({ error: 'product not found' });
  const meta = get('SELECT * FROM product_meta WHERE product_id = ? ORDER BY created_at DESC LIMIT 1', [product.id]);
  const token = getOrCreateDownloadToken(order.id, product.file_path);
  return { order, product, meta, downloadUrl: `${API_BASE_URL}/api/download/${token}` };
});

app.post('/api/deliveries/test', async (req, reply) => {
  if (!mailer) return reply.code(503).send({ error: 'SMTP not configured' });
  const { to } = req.body ?? {};
  if (!to) return reply.code(400).send({ error: 'to required' });
  await mailer.sendMail({
    from: process.env.SMTP_FROM,
    to,
    subject: 'GridOS Delivery Test',
    text: 'SMTP delivery test: OK',
    html: '<p>SMTP delivery test: <strong>OK</strong></p>'
  });
  return { ok: true };
});

app.post('/api/checkout/stripe', async (req, reply) => {
  if (!stripe) return reply.code(503).send({ error: 'Stripe not configured' });
  const { productId, successUrl, cancelUrl } = req.body ?? {};
  if (!productId) return reply.code(400).send({ error: 'productId required' });

  const product = get('SELECT * FROM products WHERE id = ?', [productId]);
  if (!product) return reply.code(404).send({ error: 'product not found' });

  const session = await stripe.checkout.sessions.create({
    mode: 'payment',
    line_items: [
      {
        price_data: {
          currency: String(product.currency).toLowerCase(),
          unit_amount: Math.round(Number(product.price) * 100),
          product_data: {
            name: product.title,
            description: product.category
          }
        },
        quantity: 1
      }
    ],
    success_url: successUrl || `${WEB_BASE_URL}/?checkout=stripe&session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: cancelUrl || `${WEB_BASE_URL}/?checkout=cancel`,
    metadata: { productId: product.id }
  });

  return { url: session.url, sessionId: session.id };
});

app.post('/api/checkout/stripe/confirm', async (req, reply) => {
  if (!stripe) return reply.code(503).send({ error: 'Stripe not configured' });
  const { sessionId } = req.body ?? {};
  if (!sessionId) return reply.code(400).send({ error: 'sessionId required' });

  const session = await stripe.checkout.sessions.retrieve(sessionId);
  const result = await processStripeSession(session);
  if (!result) return reply.code(402).send({ error: 'payment not completed' });
  return { downloadUrl: result.downloadUrl };
});

app.post('/api/checkout/paypal', async (req, reply) => {
  if (!paypalClient) return reply.code(503).send({ error: 'PayPal not configured' });
  const { productId, returnUrl, cancelUrl } = req.body ?? {};
  if (!productId) return reply.code(400).send({ error: 'productId required' });

  const product = get('SELECT * FROM products WHERE id = ?', [productId]);
  if (!product) return reply.code(404).send({ error: 'product not found' });

  const request = new paypal.orders.OrdersCreateRequest();
  request.prefer('return=representation');
  request.requestBody({
    intent: 'CAPTURE',
    purchase_units: [
      {
        amount: { currency_code: String(product.currency), value: Number(product.price).toFixed(2) },
        description: product.title,
        custom_id: product.id
      }
    ],
    application_context: {
      return_url: returnUrl || `${WEB_BASE_URL}/?checkout=paypal`,
      cancel_url: cancelUrl || `${WEB_BASE_URL}/?checkout=cancel`
    }
  });

  const response = await paypalClient.execute(request);
  const approve = response.result.links?.find((l) => l.rel === 'approve');
  return { id: response.result.id, url: approve?.href };
});

app.post('/api/checkout/paypal/capture', async (req, reply) => {
  if (!paypalClient) return reply.code(503).send({ error: 'PayPal not configured' });
  const { orderId } = req.body ?? {};
  if (!orderId) return reply.code(400).send({ error: 'orderId required' });

  const request = new paypal.orders.OrdersCaptureRequest(orderId);
  request.requestBody({});
  const response = await paypalClient.execute(request);
  if (response.result.status !== 'COMPLETED') return reply.code(402).send({ error: 'payment not completed' });

  const purchaseUnit = response.result.purchase_units?.[0];
  const productId = purchaseUnit?.custom_id;
  const product = productId ? get('SELECT * FROM products WHERE id = ?', [productId]) : null;
  if (!product) return reply.code(404).send({ error: 'product not found' });

  const existing = findOrderByProviderRef(response.result.id);
  const orderRecordId = existing?.id || recordSale({
    provider: 'paypal',
    amount: Number(product.price),
    currency: String(product.currency),
    productId: product.id,
    buyerEmail: response.result.payer?.email_address || 'unknown',
    providerRef: response.result.id
  });

  const token = getOrCreateDownloadToken(orderRecordId, product.file_path);
  const downloadUrl = `${API_BASE_URL}/api/download/${token}`;
  await deliverIfPossible(orderRecordId, response.result.payer?.email_address || 'unknown', product.title, downloadUrl);
  return { downloadUrl };
});

app.post('/api/webhooks/stripe', { config: { rawBody: true } }, async (req, reply) => {
  if (!stripe || !process.env.STRIPE_WEBHOOK_SECRET) {
    return reply.code(503).send({ error: 'Stripe webhook not configured' });
  }

  const signature = req.headers['stripe-signature'];
  if (!signature) return reply.code(400).send({ error: 'Missing stripe signature' });

  let event;
  try {
    event = stripe.webhooks.constructEvent(req.rawBody, signature, process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    return reply.code(400).send({ error: 'Invalid signature' });
  }

  if (event.type === 'checkout.session.completed' || event.type === 'checkout.session.async_payment_succeeded') {
    enqueueWebhookJob('stripe', event.type, event);
  }

  return { received: true };
});

app.get('/api/download/:token', async (req, reply) => {
  const { token } = req.params;
  const row = get('SELECT * FROM downloads WHERE token = ?', [token]);
  if (!row) return reply.code(404).send({ error: 'invalid token' });
  if (Date.now() > Number(row.expires_at)) return reply.code(410).send({ error: 'link expired' });

  if (!fs.existsSync(row.file_path)) return reply.code(404).send({ error: 'file not found' });
  reply.header('Content-Type', 'application/octet-stream');
  reply.header('Content-Disposition', `attachment; filename="${path.basename(row.file_path)}"`);
  return reply.send(fs.createReadStream(row.file_path));
});

// ------------------------

// NEU: Gemini Chat Proxy (Serverseitig, mit RAG Context)
app.post('/api/chat', async (req, reply) => {
  if (!genAI) {
    return reply.status(503).send({ error: 'Server: Kein Gemini API Key konfiguriert (siehe env/server).' });
  }

  const { message, history } = req.body || {};
  if (!message) return reply.status(400).send({ error: 'Message required' });

  try {
    const context = getRecentContext && typeof getRecentContext === 'function' ? getRecentContext() : '';
    const snapshot = getBusinessSnapshot();
    const snapshotText = formatBusinessSnapshot(snapshot);
    const executiveRole = getExecutiveRole();
    const executiveDirective = getExecutiveRoleDirective(executiveRole);

    const model = genAI.getGenerativeModel({ 
      model: 'gemini-1.5-flash',
      // Dynamischer System-Prompt mit "Tools"
      systemInstruction: `SYSTEM: Nexus "LogikX" v9 + MATHEMATIX + EXECUTIVE OPS Core.
    MODE: Hyper-Analytical + Business Operator.

    BUSINESS ROLE:
    Active profile: ${executiveRole}
    ${executiveDirective}
    Du agierst wie ein Geschaeftsoperator mit 20+ Jahren Praxis (CEO/CFO/COO-Denke).
    Jede Empfehlung muss wirtschaftlich belastbar sein und sofort umsetzbar bleiben.

    ANTWORT-RAHMEN (wenn sinnvoll):
    1) Lagebild
    2) Hebel (max 3)
    3) Risiko
    4) Naechster Schritt heute

Du bist ein Hybrid aus AI und MATHEMATIX-Engine.
1. SELF-LEARNING: Speichere User-Fakten & Variablen (z.B. "Steuersatz ist 19%").
2. MATH: Rechne NICHT im Kopf. Nutze >> CALC: für ALLES Mathematische.
    3. BUSINESS EXECUTION: Nutze datengetriebene Priorisierung, Cash-Fokus und Unit-Economics.

COMMANDS:
>> LISTEN: <Task> || <Prio>
>> LÖSCHEN: <ID>
>> BUDGET: <Betrag>
>> MERKX: <Fakt/Variable>
>> VERGISS: <ID>
>> CALC: <Math Expression> (z.B. 125 * 4.5)
    >> KPI: <metric_name>
    >> DECIDE: <Option A> || <Option B> [|| <Option C> ...]
    >> PLAN: <Goal> || <HorizonDays>
    >> ROLE: <CEO|CFO|COO>
    >> ALERTS: <overview|ack_all>

Beispiel:
User: "Mein Stundensatz ist 150. Was verdiene ich in 8h?"
Du: Ich speichere den Satz und berechne den Tagessatz.
>> MERKX: Stundensatz = 150
>> CALC: 150 * 8

KONTEXT-STREAM:
${context}
${snapshotText}`
    });

    const chat = model.startChat({
      history: history || [],
      generationConfig: { maxOutputTokens: 1000 }
    });

    const result = await chat.sendMessage(message);
    let text = result.response.text();

    // --- AGENTIC ACTION PARSER (LogikX + Mathematix) ---
    const lines = text.split('\n');
    const finalLines = [];
    for (const line of lines) {
      if (line.includes('>> LISTEN:')) {
        const [_, payload] = line.split('>> LISTEN:');
        const [title, prio] = payload.split('||').map(s => s.trim());
        const id = `task_${Date.now()}_${Math.random().toString(16).slice(2)}`;
        run('INSERT INTO tasks (id, title, done, priority, created_at) VALUES (?, ?, ?, ?, ?)', [id, title, 0, Number(prio)||2, Date.now()]);
        const row = get('SELECT * FROM tasks WHERE id=?', [id]);
        broadcast('task:created', row);
        finalLines.push(`✅ *Task:* ${title}`);
      } else if (line.includes('>> CALC:')) {
        const [_, expr] = line.split('>> CALC:');
        try {
          const resultValue = evaluateArithmeticExpression(expr);
          finalLines.push(`🧮 *Mathematix:* ${String(expr).trim()} = **${resultValue}**`);
        } catch (e) {
          finalLines.push(`⚠️ *Calc Error:* ${expr}`);
        }
      } else if (line.includes('>> KPI:')) {
        const [_, metricRaw] = line.split('>> KPI:');
        const metric = String(metricRaw || '').trim().toLowerCase();
        const kpi = getBusinessSnapshot();

        if (!metric || metric === 'all' || metric === 'overview') {
          finalLines.push(`📊 *KPI Overview:* Revenue ${kpi.revenue30} CHF | Cost ${kpi.cost30} CHF | Net ${kpi.net30} CHF | Margin ${(kpi.margin30 * 100).toFixed(1)}% | Balance ${kpi.balance} CHF | Runway ${kpi.runwayDays ?? 'n/a'} days`);
        } else if (metric.includes('margin')) {
          finalLines.push(`📈 *KPI Margin:* ${(kpi.margin30 * 100).toFixed(1)}%`);
        } else if (metric.includes('revenue') || metric.includes('umsatz')) {
          finalLines.push(`💵 *KPI Revenue (30d):* ${kpi.revenue30} CHF`);
        } else if (metric.includes('cost') || metric.includes('kosten')) {
          finalLines.push(`💸 *KPI Cost (30d):* ${kpi.cost30} CHF`);
        } else if (metric.includes('runway')) {
          finalLines.push(`⛽ *KPI Runway:* ${kpi.runwayDays ?? 'n/a'} days`);
        } else {
          finalLines.push(`ℹ️ *KPI:* Unbekannte Kennzahl "${metricRaw}". Nutze z.B. overview, margin, revenue, cost, runway.`);
        }
      } else if (line.includes('>> DECIDE:')) {
        const [_, payload] = line.split('>> DECIDE:');
        const options = String(payload || '')
          .split('||')
          .map((s) => s.trim())
          .filter(Boolean)
          .slice(0, 6);

        if (options.length < 2) {
          finalLines.push('⚠️ *Decision:* Mindestens zwei Optionen benoetigt.');
        } else {
          const activeRole = getExecutiveRole();
          const ranked = options
            .map((opt) => scoreBusinessOption(opt, snapshot, activeRole))
            .sort((a, b) => b.score - a.score);
          const winner = ranked[0];
          finalLines.push(`🎯 *Decision (${activeRole}):* Prioritaet -> **${winner.option}** (Score ${winner.score}/100)`);
          if (winner.reasons.length) finalLines.push(`   Grund: ${winner.reasons.join(' | ')}`);
        }
      } else if (line.includes('>> PLAN:')) {
        const [_, payload] = line.split('>> PLAN:');
        const [goalRaw, horizonRaw] = String(payload || '').split('||').map((s) => s.trim());
        const horizonDays = Number(horizonRaw || 14);
        const activeRole = getExecutiveRole();
        const plan = buildExecutionPlan(goalRaw, horizonDays, snapshot, activeRole);

        for (const step of plan) {
          const id = `task_${Date.now()}_${Math.random().toString(16).slice(2)}`;
          run('INSERT INTO tasks (id, title, done, priority, created_at) VALUES (?, ?, ?, ?, ?)', [
            id,
            step.title,
            0,
            Number(step.priority) || 2,
            Date.now()
          ]);
          const row = get('SELECT * FROM tasks WHERE id=?', [id]);
          broadcast('task:created', row);
        }

        finalLines.push(`🧭 *Plan erstellt (${activeRole}):* ${plan.length} Aufgaben fuer "${goalRaw || 'Business-Ziel'}" angelegt.`);
      } else if (line.includes('>> ROLE:')) {
        const [_, roleRaw] = line.split('>> ROLE:');
        const nextRole = setExecutiveRole(roleRaw);
        finalLines.push(`🧠 *Executive-Profil gesetzt:* ${nextRole}`);
      } else if (line.includes('>> ALERTS:')) {
        const [_, actionRaw] = line.split('>> ALERTS:');
        const action = String(actionRaw || '').trim().toLowerCase();

        if (action === 'ack_all') {
          run('UPDATE business_alerts SET acknowledged = 1 WHERE acknowledged = 0');
          finalLines.push('✅ *Alerts:* Alle offenen Alerts wurden bestaetigt.');
        } else {
          const list = all(
            'SELECT severity, title, message, created_at FROM business_alerts WHERE acknowledged = 0 ORDER BY created_at DESC LIMIT 5'
          );
          if (!list.length) {
            finalLines.push('🟢 *Alerts:* Keine offenen KPI-Warnungen.');
          } else {
            finalLines.push(`🚨 *Alerts (${list.length} offen):*`);
            for (const item of list) {
              finalLines.push(`- [${String(item.severity).toUpperCase()}] ${item.title}: ${item.message}`);
            }
          }
        }
      } else if (line.includes('>> LÖSCHEN:')) {
         const [_, id] = line.split('>> LÖSCHEN:');
         const trimId = id.trim();
         run('DELETE FROM tasks WHERE id = ?', [trimId]);
         broadcast('task:deleted', { id: trimId });
         finalLines.push(`🗑️ *Task gelöscht*`);
      } else if (line.includes('>> BUDGET:')) {
        const [_, val] = line.split('>> BUDGET:');
        const amount = parseFloat(val.trim());
        if (!isNaN(amount)) {
          const existing = get('SELECT value FROM global_settings WHERE key = ?', ['daily_budget']);
          if (existing) run('UPDATE global_settings SET value = ? WHERE key = ?', [String(amount), 'daily_budget']);
          else run('INSERT INTO global_settings (key, value) VALUES (?, ?)', ['daily_budget', String(amount)]);
          finalLines.push(`💰 *Budget:* ${amount} CHF`);
        }
      } else if (line.includes('>> MERKX:')) {
        const [_, fact] = line.split('>> MERKX:');
        const id = `know_${Date.now()}_${Math.random().toString(16).slice(2)}`;
        run('INSERT INTO knowledge (id, fact, created_at) VALUES (?, ?, ?)', [id, fact.trim(), Date.now()]);
        finalLines.push(`🧠 *LogikX Merkt:* "${fact.trim()}"`);
      } else if (line.includes('>> VERGISS:')) {
        const [_, id] = line.split('>> VERGISS:');
        run('DELETE FROM knowledge WHERE id = ?', [id.trim()]);
        finalLines.push(`💨 *VergissNix:* Erinnerung gelöscht.`);
      } else {
        finalLines.push(line);
      }
    }
    text = finalLines.join('\n');
    // -----------------------------

    return { text };
  } catch (err) {
    console.error('Gemini Error:', err);
    return reply.status(500).send({ error: err.message || 'Gemini API Error' });
  }
});


app.get('/ws', { websocket: true }, (conn) => {
  sockets.add(conn.socket);
  conn.socket.send(JSON.stringify({ event: 'hello', payload: { ts: Date.now() } }));
  conn.socket.on('close', () => sockets.delete(conn.socket));
});

app.get('/api/metrics', async () => {
  const tasks = get('SELECT COUNT(*) as c FROM tasks')?.c ?? 0;
  const notes = get('SELECT COUNT(*) as c FROM notes')?.c ?? 0;
  const tx = get('SELECT SUM(CASE WHEN type="expense" THEN amount ELSE 0 END) as spent, SUM(CASE WHEN type="income" THEN amount ELSE 0 END) as income FROM transactions') ?? { spent: 0, income: 0 };
  const spent = tx.spent ?? 0;
  const income = tx.income ?? 0;
  const balance = income - spent;
  const load = Math.min(100, Math.max(5, Math.round((tasks + notes) / 8)));

  const budget = Number(get('SELECT value FROM global_settings WHERE key = ?', ['daily_budget'])?.value || 100);

  return {
    load,
    multiplier: Number((1 + load / 1000).toFixed(2)),
    uptime: Math.floor(process.uptime()),
    shardsActive: Math.max(3, Math.round((tasks + notes) / 60)),
    globalIndex: Number((income * 1.3 - spent * 0.7 + 124800).toFixed(2)),
    merchantBalance: Number(balance.toFixed(2)),
    totalSpentCHF: Number(spent.toFixed(2)),
    dailyBudgetCHF: budget
  };
});

app.get('/api/business/snapshot', async () => {
  return getBusinessSnapshot();
});

app.get('/api/business/role', async () => ({
  role: getExecutiveRole(),
  directive: getExecutiveRoleDirective(getExecutiveRole())
}));

app.put('/api/business/role', async (req, reply) => {
  const { role } = req.body ?? {};
  if (!role) return reply.code(400).send({ error: 'role required (CEO|CFO|COO)' });
  const nextRole = setExecutiveRole(role);
  return { role: nextRole, directive: getExecutiveRoleDirective(nextRole) };
});

app.get('/api/business/thresholds', async () => getAlertThresholds());

app.put('/api/business/thresholds', async (req, reply) => {
  const { margin, runwayDays, criticalTasks } = req.body ?? {};

  const nextMargin = Number.isFinite(Number(margin)) ? Number(margin) : getAlertThresholds().margin;
  const nextRunway = Number.isFinite(Number(runwayDays)) ? Number(runwayDays) : getAlertThresholds().runwayDays;
  const nextCritical = Number.isFinite(Number(criticalTasks)) ? Number(criticalTasks) : getAlertThresholds().criticalTasks;

  const upsert = (key, value) => {
    const existing = get('SELECT value FROM global_settings WHERE key = ?', [key]);
    if (existing) run('UPDATE global_settings SET value = ? WHERE key = ?', [String(value), key]);
    else run('INSERT INTO global_settings (key, value) VALUES (?, ?)', [key, String(value)]);
  };

  upsert('alert_margin_threshold', nextMargin);
  upsert('alert_runway_days_threshold', nextRunway);
  upsert('alert_critical_tasks_threshold', nextCritical);

  return getAlertThresholds();
});

app.get('/api/business/alerts', async (req) => {
  const limitRaw = Number(req.query?.limit ?? 30);
  const limit = Number.isFinite(limitRaw) ? Math.max(1, Math.min(100, limitRaw)) : 30;
  return all('SELECT * FROM business_alerts ORDER BY created_at DESC LIMIT ?', [limit]);
});

app.post('/api/business/alerts/evaluate', async () => {
  const result = runEnterpriseIntelligenceCycle();
  return result;
});

app.post('/api/business/alerts/ack_all', async () => {
  run('UPDATE business_alerts SET acknowledged = 1 WHERE acknowledged = 0');
  return { ok: true };
});

app.post('/api/business/weekly/review', async () => {
  const snapshot = getBusinessSnapshot();
  const result = ensureWeeklyOpsTasks(snapshot);
  return result;
});

app.post('/api/settings/budget', async (req, reply) => {
  const { amount } = req.body ?? {};
  if (typeof amount !== 'number') return reply.code(400).send({ error: 'amount required' });
  
  const existing = get('SELECT value FROM global_settings WHERE key = ?', ['daily_budget']);
  if (existing) {
    run('UPDATE global_settings SET value = ? WHERE key = ?', [String(amount), 'daily_budget']);
  } else {
    run('INSERT INTO global_settings (key, value) VALUES (?, ?)', ['daily_budget', String(amount)]);
  }
  return { ok: true, amount };
});

// Tasks
app.get('/api/tasks', async () => {
  return all('SELECT * FROM tasks ORDER BY created_at DESC');
});

app.post('/api/tasks', async (req, reply) => {
  const { title, priority = 2 } = req.body ?? {};
  if (!title) return reply.code(400).send({ error: 'title required' });
  const id = `task_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  const created_at = Date.now();
  run('INSERT INTO tasks (id, title, done, priority, created_at) VALUES (?, ?, ?, ?, ?)', [
    id,
    String(title),
    0,
    Number(priority),
    created_at
  ]);
  const row = get('SELECT * FROM tasks WHERE id=?', [id]);
  broadcast('task:created', row);
  return row;
});

app.patch('/api/tasks/:id', async (req, reply) => {
  const { id } = req.params;
  const { title, done, priority } = req.body ?? {};
  const existing = get('SELECT * FROM tasks WHERE id=?', [id]);
  if (!existing) return reply.code(404).send({ error: 'not found' });

  const next = {
    title: title ?? existing.title,
    done: typeof done === 'number' ? done : done ? 1 : 0,
    priority: priority ?? existing.priority
  };

  run('UPDATE tasks SET title=?, done=?, priority=? WHERE id=?', [next.title, next.done, next.priority, id]);
  const row = get('SELECT * FROM tasks WHERE id=?', [id]);
  broadcast('task:updated', row);
  return row;
});

app.delete('/api/tasks/:id', async (req, reply) => {
  const { id } = req.params;
  run('DELETE FROM tasks WHERE id=?', [id]);
  broadcast('task:deleted', { id });
  return { ok: true };
});

// Notes / Memory
app.get('/api/notes', async () => all('SELECT * FROM notes ORDER BY created_at DESC'));

app.post('/api/notes', async (req, reply) => {
  const { title, body = '', tags = '' } = req.body ?? {};
  if (!title) return reply.code(400).send({ error: 'title required' });
  const id = `note_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO notes (id, title, body, tags, created_at) VALUES (?, ?, ?, ?, ?)', [
    id,
    String(title),
    String(body),
    String(tags),
    Date.now()
  ]);
  const row = get('SELECT * FROM notes WHERE id=?', [id]);
  broadcast('note:created', row);
  return row;
});

app.patch('/api/notes/:id', async (req, reply) => {
  const { id } = req.params;
  const existing = get('SELECT * FROM notes WHERE id=?', [id]);
  if (!existing) return reply.code(404).send({ error: 'not found' });

  const { title, body, tags } = req.body ?? {};
  run('UPDATE notes SET title=?, body=?, tags=? WHERE id=?', [title ?? existing.title, body ?? existing.body, tags ?? existing.tags, id]);
  const row = get('SELECT * FROM notes WHERE id=?', [id]);
  broadcast('note:updated', row);
  return row;
});

app.delete('/api/notes/:id', async (req) => {
  run('DELETE FROM notes WHERE id=?', [req.params.id]);
  broadcast('note:deleted', { id: req.params.id });
  return { ok: true };
});

// Prompts
app.get('/api/prompts', async () => all('SELECT * FROM prompts ORDER BY created_at DESC'));

app.post('/api/prompts', async (req, reply) => {
  const { title, template } = req.body ?? {};
  if (!title || !template) return reply.code(400).send({ error: 'title/template required' });
  const id = `prompt_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO prompts (id, title, template, created_at) VALUES (?, ?, ?, ?)', [
    id,
    String(title),
    String(template),
    Date.now()
  ]);
  const row = get('SELECT * FROM prompts WHERE id=?', [id]);
  return row;
});

// Knowledge (Self-Learning)
app.get('/api/knowledge', async () => all('SELECT * FROM knowledge ORDER BY created_at DESC'));

app.delete('/api/knowledge/:id', async (req, reply) => {
  const { id } = req.params;
  run('DELETE FROM knowledge WHERE id=?', [id]);
  return { ok: true };
});

// Transactions
app.get('/api/transactions', async () => all('SELECT * FROM transactions ORDER BY created_at DESC'));

app.post('/api/transactions', async (req, reply) => {
  const { type, amount, currency = 'CHF', note = '' } = req.body ?? {};
  if (!type || amount == null) return reply.code(400).send({ error: 'type/amount required' });
  const id = `txn_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO transactions (id, type, amount, currency, note, created_at) VALUES (?, ?, ?, ?, ?, ?)', [
    id,
    String(type),
    Number(amount),
    String(currency),
    String(note),
    Date.now()
  ]);
  const row = get('SELECT * FROM transactions WHERE id=?', [id]);
  broadcast('txn:created', row);
  return row;
});

// Services
app.get('/api/services', async () => all('SELECT * FROM services ORDER BY created_at DESC'));

app.post('/api/services', async (req, reply) => {
  const { name, tier = 'prod', status = 'ok', region = 'eu-central' } = req.body ?? {};
  if (!name) return reply.code(400).send({ error: 'name required' });
  const id = `svc_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO services (id, name, tier, status, region, created_at) VALUES (?, ?, ?, ?, ?, ?)', [
    id,
    String(name),
    String(tier),
    String(status),
    String(region),
    Date.now()
  ]);
  return get('SELECT * FROM services WHERE id=?', [id]);
});

app.patch('/api/services/:id', async (req, reply) => {
  const { id } = req.params;
  const existing = get('SELECT * FROM services WHERE id=?', [id]);
  if (!existing) return reply.code(404).send({ error: 'not found' });
  const { name, tier, status, region } = req.body ?? {};
  run('UPDATE services SET name=?, tier=?, status=?, region=? WHERE id=?', [name ?? existing.name, tier ?? existing.tier, status ?? existing.status, region ?? existing.region, id]);
  return get('SELECT * FROM services WHERE id=?', [id]);
});

app.delete('/api/services/:id', async (req) => {
  run('DELETE FROM services WHERE id=?', [req.params.id]);
  return { ok: true };
});

// Invoices
app.get('/api/invoices', async () => all('SELECT * FROM invoices ORDER BY created_at DESC'));

app.post('/api/invoices', async (req, reply) => {
  const { client, amount, currency = 'CHF', status = 'sent' } = req.body ?? {};
  if (!client || amount == null) return reply.code(400).send({ error: 'client/amount required' });
  const id = `inv_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO invoices (id, client, amount, currency, status, created_at) VALUES (?, ?, ?, ?, ?, ?)', [
    id,
    String(client),
    Number(amount),
    String(currency),
    String(status),
    Date.now()
  ]);
  return get('SELECT * FROM invoices WHERE id=?', [id]);
});

app.patch('/api/invoices/:id', async (req, reply) => {
  const { id } = req.params;
  const existing = get('SELECT * FROM invoices WHERE id=?', [id]);
  if (!existing) return reply.code(404).send({ error: 'not found' });
  const { client, amount, currency, status } = req.body ?? {};
  run('UPDATE invoices SET client=?, amount=?, currency=?, status=? WHERE id=?', [client ?? existing.client, amount ?? existing.amount, currency ?? existing.currency, status ?? existing.status, id]);
  return get('SELECT * FROM invoices WHERE id=?', [id]);
});

// Agent Settings
app.get('/api/agent/settings', async () => get('SELECT * FROM agent_settings LIMIT 1'));

app.put('/api/agent/settings', async (req, reply) => {
  const { mode, throttle, auto_fix } = req.body ?? {};
  const row = get('SELECT * FROM agent_settings LIMIT 1');
  if (!row) return reply.code(404).send({ error: 'no settings' });
  run('UPDATE agent_settings SET mode=?, throttle=?, auto_fix=? WHERE id=?', [mode ?? row.mode, throttle ?? row.throttle, auto_fix ?? row.auto_fix, row.id]);
  return get('SELECT * FROM agent_settings WHERE id=?', [row.id]);
});

// Media analysis (text or file)
app.post('/api/media/analyze', async (req, reply) => {
  if (req.isMultipart()) {
    const data = await req.file();
    if (!data) return reply.code(400).send({ error: 'file required' });
    const buf = await data.toBuffer();
    const summary = `File ${data.filename} (${data.mimetype})`;
    const stats = { bytes: buf.length };
    const id = `media_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    run('INSERT INTO media_analyses (id, kind, summary, stats, created_at) VALUES (?, ?, ?, ?, ?)', [
      id,
      'file',
      summary,
      JSON.stringify(stats),
      Date.now()
    ]);
    return { id, kind: 'file', summary, stats };
  }

  const { text } = req.body ?? {};
  if (!text) return reply.code(400).send({ error: 'text required' });
  const words = String(text).trim().split(/\s+/).filter(Boolean);
  const summary = `Text analysed: ${words.length} words`;
  const stats = { words: words.length, chars: String(text).length };
  const id = `media_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO media_analyses (id, kind, summary, stats, created_at) VALUES (?, ?, ?, ?, ?)', [
    id,
    'text',
    summary,
    JSON.stringify(stats),
    Date.now()
  ]);
  return { id, kind: 'text', summary, stats };
});

app.get('/api/media', async () => all('SELECT * FROM media_analyses ORDER BY created_at DESC'));

// Transcripts
app.get('/api/transcripts', async () => all('SELECT * FROM transcripts ORDER BY created_at DESC'));

app.post('/api/transcripts', async (req, reply) => {
  const { text, source = 'browser' } = req.body ?? {};
  if (!text) return reply.code(400).send({ error: 'text required' });
  const id = `trn_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  run('INSERT INTO transcripts (id, source, text, created_at) VALUES (?, ?, ?, ?)', [
    id,
    String(source),
    String(text),
    Date.now()
  ]);
  return get('SELECT * FROM transcripts WHERE id=?', [id]);
});

// Insights (derived)
app.get('/api/insights', async () => {
  const lastTx = all('SELECT * FROM transactions ORDER BY created_at DESC LIMIT 8');
  const notes = all('SELECT * FROM notes ORDER BY created_at DESC LIMIT 8');
  return {
    trend: lastTx.length ? 'active' : 'idle',
    recentTransactions: lastTx,
    recentNotes: notes
  };
});

// ML Training: tiny naive bayes with deterministic accuracy
function tokenize(text) {
  return text.toLowerCase().replace(/[^\p{L}\p{N}\s]+/gu, ' ').split(/\s+/).filter(Boolean);
}

function trainNB(samples) {
  const labels = [...new Set(samples.map((s) => s.label))];
  const labelCounts = Object.fromEntries(labels.map((l) => [l, 0]));
  const tokenCounts = Object.fromEntries(labels.map((l) => [l, {}]));
  const totalTokens = Object.fromEntries(labels.map((l) => [l, 0]));
  const vocab = new Set();

  for (const s of samples) {
    labelCounts[s.label] += 1;
    const toks = tokenize(s.text);
    for (const t of toks) {
      vocab.add(t);
      tokenCounts[s.label][t] = (tokenCounts[s.label][t] ?? 0) + 1;
      totalTokens[s.label] += 1;
    }
  }

  const vocabSize = Math.max(1, vocab.size);
  const totalSamples = samples.length;
  const priors = {};
  const likelihood = {};
  const unk = {};

  for (const l of labels) {
    priors[l] = Math.log((labelCounts[l] ?? 0) / totalSamples || 1e-12);
    const denom = totalTokens[l] + vocabSize;
    likelihood[l] = {};
    for (const t of vocab) {
      const c = tokenCounts[l][t] ?? 0;
      likelihood[l][t] = Math.log((c + 1) / denom);
    }
    unk[l] = Math.log(1 / denom);
  }

  return { labels, priors, likelihood, unk };
}

function predictNB(model, text) {
  const toks = tokenize(text);
  const scores = {};
  for (const l of model.labels) {
    let s = model.priors[l];
    for (const t of toks) s += model.likelihood[l][t] ?? model.unk[l];
    scores[l] = s;
  }
  let best = model.labels[0];
  for (const l of model.labels) if (scores[l] > scores[best]) best = l;
  return best;
}

app.post('/api/train', async () => {
  const labels = ['ops', 'market', 'infra'];
  const dataset = [];
  for (let i = 0; i < 120; i++) {
    dataset.push({ label: 'ops', text: `ops shard grid node uptime ${i}` });
    dataset.push({ label: 'market', text: `market trend revenue growth ${i}` });
    dataset.push({ label: 'infra', text: `infra region service latency ${i}` });
  }

  // split
  const test = dataset.filter((_, i) => i % 5 === 0);
  const train = dataset.filter((_, i) => i % 5 !== 0);

  const model = trainNB(train);
  let correct = 0;
  for (const s of test) if (predictNB(model, s.text) === s.label) correct += 1;
  const acc = correct / test.length;

  return {
    samples: dataset.length,
    test: test.length,
    accuracy: acc
  };
});

const port = Number(process.env.PORT ?? 4000);
const host = '0.0.0.0';

app.listen({ port, host });
console.log(`[api] listening on http://${host}:${port}`);
